version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - .:/app

  db:
    image: alpine  # Using a lightweight base image
    volumes:
      - ./students.db:/students.db
